### ISSUE TITLE
Heatmaps less useful on "responsive" layouts

### ISSUE THREAD

**Issue by kraln** [padams/Open-Web-Analytics#37] opened 2014-12-12 23:36 UTC
Hi,

We have a website that's "responsive", there are several media queries (mobile, narrow, full, wide, etc) that change the layout of the site depending on the width. The heatmaps feature is really nice, but it completely falls apart on some of our pages that do interesting things with the media queries.

I thought that a solution might be using relative positions instead of pixels (i.e. x = 10% from left side of screen vs x = 130px), but that doesn't solve the vertical-space changes brought about by the media queries.

I'm trying to come up with a concept for how to address this without going crazy--maybe something to monitor media queries--but I am coming up blank.

Other than that, the default z-index of 99 for the overlay is too low, the chance that elements have a z-index of over 100 is pretty high. Everything else is dandy though, keep up the good work :)

Cheers,
Kraln

**Comment by padams** [comment] 2015-04-02 02:16
Agreed. This needs some work. ideas?

**Comment by kraln** [comment] 2015-04-02 09:03
I think the only reasonable way is to hook/capture DOM sizes and change events. That way the captured data can be separated by display size, and gain meaning

**Comment by pratham2003** [comment] 2015-05-02 14:08
I noticed that the heat map loads browser's height and width too behind the scenes.
i.e. { page_height: "522", page_width: "360" }

It should be possible to segregate the data based on this.

**Comment by ayurmedia** [comment] 2015-10-22 03:07
Hi, i noticed the same problem with other tools like ptengine.com. My idea to solve the problem is the following. For the DOM replay, single Page-View it could be fixed by recording the page_height and page_width eg. window-size with the mouse and scrolling events and during replay where the virtual mouse is shown then the page is loaded into an iframe and the dimensions of the iframe is set to these original-device dimensions. this way the html and media-queries should be applied again during the replay and the positions even with pixel-based x,y coordinates should be correct. if a tablet user changes orientation then even during one session the page_height, page_width would change, so on each frame of the replay animation the iframe-size would need to be updated. 

Then a solution for the heatmap could be to record the interesting DOM elements instead of the body x,y coordinates. i would suggest to listen for hover events on a-href links, form-elements like buttons, and images. or a more generic approach could be to find the target of a click or hover, eg. to find the element which is currently below the mouse position, i think its possible to find the element of a mouse event. then to either simply store the elements id or class, or more exact to store the xpath of the dom-element which hopefully can be found again during the generation of the overlay. 
this then will result in less precise positioning of the heatmap dots, because it only tracks a large are for a complete link, button or image. to increase the precision then inside the dom-element the relative position of the mouse to the top,left of the element eg. button can be messured in pixels, similar to the x,y position relative to body in the moment. then with the width and height of the dom element, a relative position inside the dom-element can be calculated in percentages. then during generation of the headmap dots this position can be calculated again on the now visible document. the positions will now be scaled correctly to the monitored DOM-Elements. The relative positioning inside the DOM-Element should lead to relative precise results. So if in a tablet media-query the button double in width in pixels, then center of the button, eg. the mouse is in the center of the button will be 50%, 50% which will lead to the diagram later to put a dot into the middle of the button again, which is the expected result. even if a button is fluid and will be shown in 2 lines of text and the ratio of height to width in tablet and desktop-view is different, the relative position of the mouse will still be useful. additionally there should be a device-type-filter in the headmap-overlay to set the layout to phone, tablet or desktop so that only the clicks from these devices are shown, as users on phones might have different usage behavior than desktop users, especially the scrolling will differ a lot comparing a 24" 1080p Monitor, compared to a 5" iphone. a mixed view of all clicks with the normalized heatmap dots is still useful, as it shows the general clickstreams, eg. do users use the navigation a lot etc. 
Also similar to the chome or firefox device emulator where you can set different display-dimensions where the page reflows with the media-query css for this display size, a draggable iframe could be in the page which contains the heatmap, so that you can watch the heatmap in different sizes. But probably you can also achieve this effect by simply resizing the browser-window which should trigger the media querys or using the Emulation mode in Chrome or Firefox. 
A window onresize event listener should then be used to repaint the heatmap overlay if the window-size changes because the heatmap dots then are out of sync, but a simple repaint which is based on the dom elements and the relative position inside the dom-elements should then be correct again.

**Comment by N-Upchurch** [comment] 2016-02-25 03:36
I wish I had the know-how to contribute! It would be really useful to resolve this.

**Comment by ayurmedia** [comment] 2016-02-28 11:05
@N-Upchurch i don't use OWA anymore, as its slow and the development of the project (activitiy) is dead. i use PIWIK instead, which has some active development and similiar features like OWA. Or simply stick with google analytics + API.

**Closed** 2020-03-11 06:15 UTC
Labels: enhancement
