### ISSUE TITLE
PHP 7.0 / 7.1 support, install wizard shows blank screen and warnings ?

### ISSUE THREAD

**Issue by sapcode** [padams/Open-Web-Analytics#242] opened 2017-04-02 11:48 UTC
Dear owa team,
i tried installing owa on PHP 7.0 / 7.1 but it was not possible to overcome the install wizard, just a blank screen. Furthermore minor warnings were shown on the top of the install wizard.
Best regards

**Comment by padams** [comment] 2017-04-02 14:46
Try the code from master.

**Comment by n2bh** [comment] 2017-04-20 18:40
Same Issue here on CentOS 6.9, both with tarball and master.

After filling in DB details, I get a blank page at 

.php?install.php?owa_action=base.installCheckEnv

If I create the config file from command line, I get the follwoing errors

$ touch owa-config.php
$ chmod 0777 owa-config.php
$ chown root.root owa-config.php
$ php cli.php cmd=install

PHP Fatal error:  Uncaught Error: Class 'owa_db_' not found in /usr/share/owa/owa_coreAPI.php:102
Stack trace:
#0 /usr/share/owa/owa_coreAPI.php(86): owa_coreAPI::dbFactory()
#1 /usr/share/owa/owa_entity.php(370): owa_coreAPI::dbSingleton()
#2 /usr/share/owa/owa_entity.php(340): owa_entity->getByColumn('id', '1')
#3 /usr/share/owa/modules/base/classes/settings.php(271): owa_entity->getByPk('id', '1')
#4 /usr/share/owa/owa_caller.php(100): owa_settings->load('1')
#5 /usr/share/owa/cli.php(60): owa_caller->__construct()
#6 {main}
  thrown in /usr/share/owa/owa_coreAPI.php on line 102

Running on a development server with with PHP 7.1.4

**Comment by padams** [comment] 2017-04-26 20:17
can you turn on debugging on see what errors are throw when you get hat blank page? 

The Fatal error you mention above is due to not defining the db_type constant as 'mysql' in the config file.

**Comment by dannycoulombe** [comment] 2017-05-18 16:27
I had the same issue. The problem is that /plugins/db/owa_db_mysql.php is using deprecated mysql functions. A quick fix was to search and replace "mysql_" to "mysqli_".

**Comment by dannycoulombe** [comment] 2017-05-18 16:50
There are other issues in other pages. I may try to fix it soon.

<br />
<b>Notice</b>:  Array to string conversion in <b>/web/stats.dannycoulombe.com/modules/base/classes/paginatedResultSet.php</b> on line <b>237</b><br />
<br />
<b>Notice</b>:  Undefined property: owa_paginatedResultSet::$Array in <b>/web/stats.dannycoulombe.com/modules/base/classes/paginatedResultSet.php</b> on line <b>237</b><br />
Function name must be a string // #0 /web/stats.dannycoulombe.com/modules/base/module.php(2719): owa_paginatedResultSet->formatResults('json')
#1 /web/stats.dannycoulombe.com/owa_coreAPI.php(564): owa_baseModule->getResultSet('visits,pagesPer...', 'country,country...', 'c71d918f60b5b6f...', '', 'visits-', '30', '', '', 'last_seven_days', '', '', '', '', 'json', '')
#2 /web/stats.dannycoulombe.com/modules/base/apiRequest.php(75): owa_coreAPI::executeApiCommand(Array)
#3 /web/stats.dannycoulombe.com/modules/base/apiRequest.php(69): owa_apiRequestController->action()
#4 /web/stats.dannycoulombe.com/owa_coreAPI.php(788): owa_apiRequestController->doAction()
#5 /web/stats.dannycoulombe.com/owa_coreAPI.php(1211): owa_coreAPI::performAction('base.apiRequest', Array)
#6 /web/stats.dannycoulombe.com/owa_caller.php(232): owa_coreAPI::handleRequest('', 'base.apiRequest')
#7 /web/stats.dannycoulombe.com/api.php(43): owa_caller->handleRequest('', 'base.apiRequest')
#8 {main}

**Comment by padams** [comment] 2017-05-18 17:15
This is fixed in master I believe.

**Comment by dannycoulombe** [comment] 2017-05-18 18:33
> This is fixed in master I believe.

Indeed, well... that'll teach me! ^^

**Comment by dlotton** [comment] 2017-09-20 16:19
Downloading the master branch fixed the problem with the installer screen going to a blank screen.  Now having problems when trying to create a new tracked site profile.  When saving settings it renders a blank screen (similar to how the install page behaved).  

Apache error.log shows a complaint about an undefined index in Log.php.  If I remember correctly, this is similar to the error that was being thrown by the installer page before I downloaded the master branch to fix the php7 problem.

Lingering PHP7 issue in the master branch?

**Comment by padams** [comment] 2017-09-21 08:24
Can you post the error here?

**Comment by dlotton** [comment] 2017-09-21 12:56
Here's what's showing up in the apache error.log.

`[Wed Sep 20 10:07:23.545843 2017] [:error] [pid 2836] [client 10.129.4.161:53164] PHP Notice:  Undefined index:  in /var/www/owa/includes/Log-1.13.1/Log.php on line 593, referer: http://xxx.yyy.zzz.com/owa/index.php?owa_do=base.sitesProfile`
 
I'm pretty certain this is the same error that was posting when I couldn't get the installer to work.  I then downloaded the master branch and thing seemed to be going fine until I tried to create a new tracked site.

**Comment by padams** [comment] 2017-10-25 03:22
Let me know if this doesn't fix your issue.

**Closed** 2017-10-25 03:21 UTC

**Comment by eboisen** [comment] 2017-10-25 19:59
Hello padams,


I appreciate you looking at this.  I substituted six old files with the new ones. The only page I can seem to open is:

owa/install.php

Clicking on "Let's get Started" from there results in HTTP ERROR 500


I have looked through the install documentation and do not really see any other avenues to try.  Any help would be appreciated.


Regards,


Erik




________________________________

**Comment by eboisen** [comment] 2017-10-25 20:59
Hi padams,


I restarted Apache and it seems to be working now.  Kind of odd the user name is admin with the password I used for root.  I don't see this anywhere in the documentation.


Thanks again.


Regards,


Erik


________________________________

**Comment by padams** [comment] 2017-10-26 03:04
Admin is the default username but the password is not pulled from anywhere. It has to be entered by the user during install.

**Comment by rosnaib11** [comment] 2018-08-13 08:04
Hi can someone help me with my OWA? I am new here.. I have a web server running in centos7, i followed everything found in documentation.. I entered all the correct details in owa-config.php When in the login page, I'd just enetered admin as user and leave the password blank as I didn't remember I assigned any password in my installation. When I hit enter, it became HTTP 500 Internal server error. ANd until now, it's still error. 

I'm receiving install.php?owa_action=base.installCheckEnv then blank page.

Please. help.
