### ISSUE TITLE
Can't login to fresh install

### ISSUE THREAD

**Issue by squarepegsys** [padams/Open-Web-Analytics#71] opened 2015-04-17 11:23 UTC
I just installed OWA on a freshly installed Linux box. I setup myself as the initial user and the installer displayed my admin user and password but I can't login with it.   When I log in it stays on the login screen with no message. If I put in the wrong password I get the red box that says "Login Failed....". So authentication is working but it's not allowing me in.

I turned on logging but don't see anything in the logs.

I don't have DNS on this server setup yet so I'm using the IP Address. Other than that I can't think of anything weird or different I'm going.

**Comment by padams** [comment] 2015-04-17 12:37
Two things to try:

- run OWA under a fully qualified domain name not an IP address. 

- Disable MySQL strict mode

**Comment by mbrown1413** [comment] 2018-02-21 19:16
I have the same exact problem. It turns out I was running into issue #210. Switching from Chrome to Firefox allowed me to log in.

**Comment by padams** [comment] 2018-02-21 20:17
I can't reproduce this. are you running an ad blocker or something that would not allow OWA to set its cookies. Best bet is to turn on development logging in the config file and then check the error log to see where OWA is getting hung up.

**Comment by siva538** [comment] 2018-05-11 13:49
I had exactly the same issue with latest owa 1.6.1, and chrome browser 66.0.3359.139 version. 

The work-around is to browse the site using Firefox browser. 

Thanks much mbrown for your help with the feedback.

**Comment by padams** [comment] 2020-03-11 05:44
Closing as we will deal with Chrome in #210

**Closed by padams** 2020-03-11 05:44 UTC
