### ISSUE TITLE
Announce New Visitors Via E-mail

### ISSUE THREAD

**Issue by n0taga1n** [padams/Open-Web-Analytics#420] opened 2019-08-26 14:00 UTC
Hi All,
Is there a solution to this functionality not working? I have trawled the forum, tried some of the suggestions but none which have worked for me. I also cannot find any clues of where to start looking in any of the log files.
Any suggestions? 
Tia

**Comment by padams** [comment] 2019-09-06 06:48
Are you getting any of the admin emails that OWA sends (ie. when you create a new user or forget your password)? If not, the issue is likely in the way your PHP instance is configured to send mail.

If you are getting those emails then there is a bug. Turn on development logging and initiate a visit. You will see the email notification handler kick in and fail somewhere in the log file.

**Comment by n0taga1n** [comment] 2019-09-07 18:12
Hi, I'm receiving all the admin emails, new user and password reset. The following info maybe of help.

Tia
---
<datetime>2019-09-07 09:32:25 (BST)</datetime>
	<errornum>8</errornum>
	<errormsg>Undefined variable: host_name</errormsg>
	<scriptname>/modules/base/classes/trackingEventHelpers.php</scriptname>
	<scriptlinenum>543</scriptlinenum>
</errorentry>

 
09:32:25 2019-09-07 3804 [debug_log] <errorentry>
	<datetime>2019-09-07 09:32:25 (BST)</datetime>
	<errornum>2</errornum>
	<errormsg>dns_get_record(): An unexpected server failure occurred.</errormsg>
	<scriptname>/modules/base/classes/trackingEventHelpers.php</scriptname>
	<scriptlinenum>543</scriptlinenum>
</errorentry>

 
09:32:25 2019-09-07 3804 [debug_log] <errorentry>
	<datetime>2019-09-07 09:32:25 (BST)</datetime>
	<errornum>8</errornum>
	<errormsg>Undefined variable: remote_host</errormsg>
	<scriptname>/modules/base/classes/trackingEventHelpers.php</scriptname>
	<scriptlinenum>554</scriptlinenum>
</errorentry>

 
09:32:25 2019-09-07 3804 [debug_log]  
09:32:25 2019-09-07 3804 [debug_log] <errorentry>
	<datetime>2019-09-07 09:32:25 (BST)</datetime>
	<errornum>8</errornum>
	<errormsg>Undefined variable: remote_host</errormsg>
	<scriptname>/modules/base/classes/trackingEventHelpers.php</scriptname>
	<scriptlinenum>555</scriptlinenum>
</errorentry>

------------------
09:32:25 2019-09-07 3804 [debug_log] EHS: Responses - Array
(
    [owa_visitorUpdateHandlers] => 
    [owa_refererHandlers] => 2
    [owa_searchTermHandlers] => 2
    [owa_osHandlers] => 2
    [owa_sourceHandlers] => 2
    [owa_campaignHandlers] => 2
    [owa_adHandlers] => 2
    [owa_userAgentHandlers] => 2
    [owa_hostHandlers] => 2
    [owa_visitorHandlers] => 2
    [owa_locationHandlers] => 2
    [owa_conversionHandlers] => 2
    [owa_notifyHandlers] => 2
)

09:32:25 2019-09-07 3804 [debug_log] EHS: Responses - Array
(
    [owa_sessionHandlers] => 2
    [owa_refererHandlers] => 2
    [owa_searchTermHandlers] => 2
    [owa_osHandlers] => 2
    [owa_sourceHandlers] => 2
    [owa_campaignHandlers] => 2
    [owa_adHandlers] => 2
    [owa_userAgentHandlers] => 2
    [owa_hostHandlers] => 2
    [owa_visitorHandlers] => 2
    [owa_locationHandlers] => 2
    [owa_documentHandlers] => 2
)

**Comment by padams** [comment] 2020-03-11 06:54
Fixed in master.

**Closed by padams** 2020-03-11 06:54 UTC
Labels: question
